// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Routify.Logistica.Data;

#nullable disable

namespace Routify.Logistica.Data.Migrations
{
    [DbContext(typeof(LogisticaDbContext))]
    partial class LogisticaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Routify.Logistica.Models.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("cliente_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ClienteId"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("apellido");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .HasColumnType("text")
                        .HasColumnName("telefono");

                    b.HasKey("ClienteId")
                        .HasName("pk_clientes");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_clientes_email");

                    b.ToTable("clientes", (string)null);
                });

            modelBuilder.Entity("Routify.Logistica.Models.Direccion", b =>
                {
                    b.Property<int>("DireccionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("direccion_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DireccionId"));

                    b.Property<string>("Calle")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("calle");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("ciudad");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("integer")
                        .HasColumnName("cliente_id");

                    b.Property<string>("CodigoPostal")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("codigo_postal");

                    b.Property<decimal?>("Latitud")
                        .HasColumnType("numeric")
                        .HasColumnName("latitud");

                    b.Property<decimal?>("Longitud")
                        .HasColumnType("numeric")
                        .HasColumnName("longitud");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("numero");

                    b.Property<string>("Provincia")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("provincia");

                    b.HasKey("DireccionId")
                        .HasName("pk_direcciones");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("ix_direcciones_cliente_id");

                    b.ToTable("direcciones", (string)null);
                });

            modelBuilder.Entity("Routify.Logistica.Models.Envio", b =>
                {
                    b.Property<int>("EnvioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("envio_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EnvioId"));

                    b.Property<decimal?>("CostoEnvio")
                        .HasColumnType("numeric")
                        .HasColumnName("costo_envio");

                    b.Property<int>("DireccionDestinoId")
                        .HasColumnType("integer")
                        .HasColumnName("direccion_destino_id");

                    b.Property<int>("DireccionOrigenId")
                        .HasColumnType("integer")
                        .HasColumnName("direccion_origen_id");

                    b.Property<string>("EstadoActual")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado_actual");

                    b.Property<DateTime?>("FechaEntregaEstimada")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_entrega_estimada");

                    b.Property<DateTime>("FechaEnvio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_envio");

                    b.Property<int>("PedidoId")
                        .HasColumnType("integer")
                        .HasColumnName("pedido_id");

                    b.Property<Guid?>("RepartidorUsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("repartidor_usuario_id");

                    b.Property<int?>("VehiculoId")
                        .HasColumnType("integer")
                        .HasColumnName("vehiculo_id");

                    b.HasKey("EnvioId")
                        .HasName("pk_envios");

                    b.HasIndex("DireccionDestinoId")
                        .HasDatabaseName("ix_envios_direccion_destino_id");

                    b.HasIndex("DireccionOrigenId")
                        .HasDatabaseName("ix_envios_direccion_origen_id");

                    b.HasIndex("PedidoId")
                        .IsUnique()
                        .HasDatabaseName("ix_envios_pedido_id");

                    b.HasIndex("VehiculoId")
                        .HasDatabaseName("ix_envios_vehiculo_id");

                    b.ToTable("envios", (string)null);
                });

            modelBuilder.Entity("Routify.Logistica.Models.HistorialEstadoEnvio", b =>
                {
                    b.Property<int>("HistorialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("historial_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HistorialId"));

                    b.Property<int>("EnvioId")
                        .HasColumnType("integer")
                        .HasColumnName("envio_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_hora");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.Property<Guid?>("UsuarioResponsableId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_responsable_id");

                    b.HasKey("HistorialId")
                        .HasName("pk_historial_estados_envio");

                    b.HasIndex("EnvioId")
                        .HasDatabaseName("ix_historial_estados_envio_envio_id");

                    b.ToTable("historial_estados_envio", (string)null);
                });

            modelBuilder.Entity("Routify.Logistica.Models.Pago", b =>
                {
                    b.Property<int>("PagoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("pago_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PagoId"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaPago")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_pago");

                    b.Property<string>("IdTransaccionExterna")
                        .HasColumnType("text")
                        .HasColumnName("id_transaccion_externa");

                    b.Property<string>("MedioPago")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("medio_pago");

                    b.Property<decimal>("MontoPagado")
                        .HasColumnType("numeric")
                        .HasColumnName("monto_pagado");

                    b.Property<int>("PedidoId")
                        .HasColumnType("integer")
                        .HasColumnName("pedido_id");

                    b.HasKey("PagoId")
                        .HasName("pk_pagos");

                    b.HasIndex("PedidoId")
                        .IsUnique()
                        .HasDatabaseName("ix_pagos_pedido_id");

                    b.ToTable("pagos", (string)null);
                });

            modelBuilder.Entity("Routify.Logistica.Models.Paquete", b =>
                {
                    b.Property<int>("PaqueteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("paquete_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PaqueteId"));

                    b.Property<decimal>("Alto")
                        .HasColumnType("numeric")
                        .HasColumnName("alto");

                    b.Property<decimal>("Ancho")
                        .HasColumnType("numeric")
                        .HasColumnName("ancho");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<decimal>("Largo")
                        .HasColumnType("numeric")
                        .HasColumnName("largo");

                    b.Property<int>("PedidoId")
                        .HasColumnType("integer")
                        .HasColumnName("pedido_id");

                    b.Property<decimal>("PesoKg")
                        .HasColumnType("numeric")
                        .HasColumnName("peso_kg");

                    b.Property<decimal>("ValorDeclarado")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_declarado");

                    b.HasKey("PaqueteId")
                        .HasName("pk_paquetes");

                    b.HasIndex("PedidoId")
                        .HasDatabaseName("ix_paquetes_pedido_id");

                    b.ToTable("paquetes", (string)null);
                });

            modelBuilder.Entity("Routify.Logistica.Models.Pedido", b =>
                {
                    b.Property<int>("PedidoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("pedido_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PedidoId"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer")
                        .HasColumnName("cliente_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaPedido")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_pedido");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.HasKey("PedidoId")
                        .HasName("pk_pedidos");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("ix_pedidos_cliente_id");

                    b.ToTable("pedidos", (string)null);
                });

            modelBuilder.Entity("Routify.Logistica.Models.Vehiculo", b =>
                {
                    b.Property<int>("VehiculoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("vehiculo_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VehiculoId"));

                    b.Property<decimal>("CapacidadKg")
                        .HasColumnType("numeric")
                        .HasColumnName("capacidad_kg");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<string>("Patente")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("patente");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.HasKey("VehiculoId")
                        .HasName("pk_vehiculos");

                    b.HasIndex("Patente")
                        .IsUnique()
                        .HasDatabaseName("ix_vehiculos_patente");

                    b.ToTable("vehiculos", (string)null);
                });

            modelBuilder.Entity("Routify.Logistica.Models.Direccion", b =>
                {
                    b.HasOne("Routify.Logistica.Models.Cliente", "Cliente")
                        .WithMany("Direcciones")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_direcciones_clientes_cliente_id");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Routify.Logistica.Models.Envio", b =>
                {
                    b.HasOne("Routify.Logistica.Models.Direccion", "DireccionDestino")
                        .WithMany()
                        .HasForeignKey("DireccionDestinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_envios_direcciones_direccion_destino_id");

                    b.HasOne("Routify.Logistica.Models.Direccion", "DireccionOrigen")
                        .WithMany()
                        .HasForeignKey("DireccionOrigenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_envios_direcciones_direccion_origen_id");

                    b.HasOne("Routify.Logistica.Models.Pedido", "Pedido")
                        .WithOne("Envio")
                        .HasForeignKey("Routify.Logistica.Models.Envio", "PedidoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_envios_pedidos_pedido_id");

                    b.HasOne("Routify.Logistica.Models.Vehiculo", "Vehiculo")
                        .WithMany("Envios")
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_envios_vehiculos_vehiculo_id");

                    b.Navigation("DireccionDestino");

                    b.Navigation("DireccionOrigen");

                    b.Navigation("Pedido");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("Routify.Logistica.Models.HistorialEstadoEnvio", b =>
                {
                    b.HasOne("Routify.Logistica.Models.Envio", "Envio")
                        .WithMany("Historial")
                        .HasForeignKey("EnvioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_historial_estados_envio_envios_envio_id");

                    b.Navigation("Envio");
                });

            modelBuilder.Entity("Routify.Logistica.Models.Pago", b =>
                {
                    b.HasOne("Routify.Logistica.Models.Pedido", "Pedido")
                        .WithOne("Pago")
                        .HasForeignKey("Routify.Logistica.Models.Pago", "PedidoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pagos_pedidos_pedido_id");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("Routify.Logistica.Models.Paquete", b =>
                {
                    b.HasOne("Routify.Logistica.Models.Pedido", "Pedido")
                        .WithMany("Paquetes")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_paquetes_pedidos_pedido_id");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("Routify.Logistica.Models.Pedido", b =>
                {
                    b.HasOne("Routify.Logistica.Models.Cliente", "Cliente")
                        .WithMany("Pedidos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pedidos_clientes_cliente_id");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Routify.Logistica.Models.Cliente", b =>
                {
                    b.Navigation("Direcciones");

                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("Routify.Logistica.Models.Envio", b =>
                {
                    b.Navigation("Historial");
                });

            modelBuilder.Entity("Routify.Logistica.Models.Pedido", b =>
                {
                    b.Navigation("Envio");

                    b.Navigation("Pago");

                    b.Navigation("Paquetes");
                });

            modelBuilder.Entity("Routify.Logistica.Models.Vehiculo", b =>
                {
                    b.Navigation("Envios");
                });
#pragma warning restore 612, 618
        }
    }
}
